theme = "catppuccin_macchiato"

[editor.file-picker]
hidden = false # show dotfiles
#git-ignore = true # don't show files in .gitignore

[keys.normal]
# just use esc instead of ; or , when selecting text or using multi-cursors
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"

# https://docs.helix-editor.com/remapping.html
[keys.insert]
C-s = ":w"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
