[[language]]
name = "rust"
auto-format = true

# config = { yaml = { schemas = { kubernetes = "/*.yaml" }, format = { enable = true } } }

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
# language-server = { command = "yaml-language-server", args = ["--stdio"] }
injection-regex = "yml|yaml"

[[grammar]]
name = "yaml"
source = { git = "https://github.com/ikatyang/tree-sitter-yaml", rev = "0e36bed171768908f331ff7dff9d956bae016efb" }

